package net.rockiecraft.foundaton.registry.fluids;

import earth.terrarium.botarium.api.registry.fluid.FluidData;
import earth.terrarium.botarium.api.registry.fluid.FluidProperties;
import earth.terrarium.botarium.api.registry.fluid.FluidRegistry;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.pathfinder.BlockPathTypes;
import net.rockiecraft.CreateMoreFarmables;


public class AllFluidProperties {

    public static final FluidRegistry FLUID_PROPERTIES = new FluidRegistry(CreateMoreFarmables.MOD_ID);

//    public static final CreateMoreFarmablesFluidRegistry FLUIDS = CreateMoreFarmablesFluidRegistry.create(CreateMoreFarmables.REGISTRIES);

//    public static final FluidData _DYED_WATER = FLUID_PROPERTIES.register("_dyed_water", FluidProperties.create()
//            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
//            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
//            .overlay(new ResourceLocation("block/water_overlay"))
//            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
//            .viscosity(1000)
//            .density(1000)
//            .tintColor()
//            .pathType(BlockPathTypes.WATER)
//            .canSwim(true)
//            .canDrown(true)
//            .canConvertToSource(true)
//            .tickRate(5));

        public static final FluidData LIQUID_QUARTZ = FLUID_PROPERTIES.register("liquid_quartz", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/liquid_quartz"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_liquid_quartz"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(6000)
            .density(3000)
            .tintColor(-393218)
            .pathType(BlockPathTypes.LAVA)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(20));
        public static final FluidData LIQUID_REDSTONE = FLUID_PROPERTIES.register("liquid_redstone", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/liquid_redstone"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_liquid_redstone"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(6000)
            .density(3000)
            .tintColor(-5231066)
            .pathType(BlockPathTypes.LAVA)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(20));
        public static final FluidData MOLTEN_ENDSTONE = FLUID_PROPERTIES.register("molten_endstone", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/molten_endstone"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_molten_endstone"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(6000)
            .density(3000)
            .tintColor(-75715)
            .pathType(BlockPathTypes.LAVA)
            .canSwim(true)
            .canDrown(false)
            .canConvertToSource(false)
            .temperature(1300)
            .tickRate(30));

    public static final FluidData WHITE_DYED_WATER = FLUID_PROPERTIES.register("white_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-393218)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

    public static final FluidData LIGHT_GRAY_DYED_WATER = FLUID_PROPERTIES.register("light_gray_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-6447721)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

        public static final FluidData GRAY_DYED_WATER = FLUID_PROPERTIES.register("gray_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-12103854)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

        public static final FluidData BLACK_DYED_WATER = FLUID_PROPERTIES.register("black_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-14869215)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

        public static final FluidData BROWN_DYED_WATER = FLUID_PROPERTIES.register("brown_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-8170446)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

        public static final FluidData RED_DYED_WATER = FLUID_PROPERTIES.register("red_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-5231066)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

        public static final FluidData ORANGE_DYED_WATER = FLUID_PROPERTIES.register("orange_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-425955)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

        public static final FluidData YELLOW_DYED_WATER = FLUID_PROPERTIES.register("yellow_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-75715)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

        public static final FluidData GREEN_DYED_WATER = FLUID_PROPERTIES.register("green_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-10585066)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

        public static final FluidData LIME_DYED_WATER = FLUID_PROPERTIES.register("lime_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-8337633)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

        public static final FluidData CYAN_DYED_WATER = FLUID_PROPERTIES.register("cyan_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-15295332)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

        public static final FluidData LIGHT_BLUE_DYED_WATER = FLUID_PROPERTIES.register("light_blue_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-12930086)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

        public static final FluidData BLUE_DYED_WATER = FLUID_PROPERTIES.register("blue_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-12827478)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

        public static final FluidData PURPLE_DYED_WATER = FLUID_PROPERTIES.register("purple_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-7785800)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

        public static final FluidData MAGENTA_DYED_WATER = FLUID_PROPERTIES.register("magenta_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-3715395)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));

        public static final FluidData PINK_DYED_WATER = FLUID_PROPERTIES.register("pink_dyed_water", FluidProperties.create()
            .still(new ResourceLocation("create_more_farmables:block/white_dyed_water"))
            .flowing(new ResourceLocation("create_more_farmables:block/flowing_dyed_water"))
            .overlay(new ResourceLocation("block/water_overlay"))
            .screenOverlay(new ResourceLocation("textures/misc/underwater.png"))
            .viscosity(1000)
            .density(1000)
            .tintColor(-816214)
            .pathType(BlockPathTypes.WATER)
            .canSwim(true)
            .canDrown(true)
            .canConvertToSource(true)
            .tickRate(5));




}
