plugins {
    id 'io.github.pacifistmc.forgix' version '2.+'
}

forgix {
    archiveBaseName = "c_more_farmables"
    archiveVersion = mod_version
    destinationDirectory = layout.projectDirectory.dir("build/forgix")

    multiversion {
        archiveBaseName = "c_more_farmables"
        archiveVersion = mod_version
        archiveClassifier = "universal"

        inputJars = files(
                "build/libs/c_more_farmables-1.19.2-${mod_version}-combo.jar",
                "build/libs/c_more_farmables-1.20.1-${mod_version}-combo.jar",
                "build/libs/create_more_farmables-${mod_version}.jar"
        )
    }
}

