# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.8.5
maven_group = net.rockiecraft
archives_name = c_more_farmables_beta
displayName = Create: More Farmables
mod_license=MIT
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
architectury_api_version = 9.2.14
botarium_version=2.3.3
resourcefulLibVersion=2.1.29
ponder_forge_version = 1.0.91
forge_config_api_port_version = 8.0.0
critter_version=0.1-beta.14


# forge
forge_version = 1.20.1-47.4.16
create_forge_version=6.0.7-281
create_forge_range=[6.0.7,)

# fabric
create_fabric_version=6.0.7.0+mc1.20.1-build.1716
create_fabric_range=>=6.0.7.0
fabric_loader_version = 0.18.3
fabric_api_version = 0.92.6+1.20.1