plugins {
    id 'dev.architectury.loom' version '1.11-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'com.gradleup.shadow' version '8.3.6'
    id "io.github.pacifistmc.forgix" version "2.+"
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version

    repositories {
        maven {
            name = "Resourceful Maven"
            description = "Baubly, Botarium & ResourcefulLib"
            url = "https://maven.teamresourceful.com/repository/maven-public/"
        }
        maven {
            url "https://cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
        maven {
            name = "Terraformers"
            url = "https://maven.terraformersmc.com/"
        }

    }

}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'

    base {
        archivesName = "$rootProject.archives_name-$project.name"
    }

    repositories {
        maven {
            name = "Resourceful Maven"
            description = "Baubly, Botarium & ResourcefulLib"
            url = "https://maven.teamresourceful.com/repository/maven-public/"
        }
        maven {
            url "https://cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
    }

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
        mappings loom.officialMojangMappings()
    }

    java {
        // if it is present.
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 17
    }

    // Configure Maven publishing.
    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = base.archivesName.get()
                from components.java
            }
        }

        // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
        repositories {
            // Notice: This block does NOT have the same function as the block in the top level.
            // The repositories here will be used for publishing your artifact, not for
            // retrieving dependencies.
        }
    }
}

forgix {
    destinationDirectory = layout.projectDirectory.dir("../build/libs")
    archiveClassifier = "combo"
    archiveVersion = minecraft_version+"-"+mod_version
    archiveBaseName = "c_more_farmables"
    fabric()
    forge()

    fabric {
        // Use the project object directly to get the task
        inputJar = project(":fabric").tasks.remapJar.archiveFile
    }

    forge {
        inputJar = project(":forge").tasks.remapJar.archiveFile
    }
    autoRun = true
}

tasks.named('mergeJars') {
    dependsOn tasks.named('build')
}
build.dependsOn(":fabric:build")
build.dependsOn(":forge:build")