# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.9.0
maven_group = net.rockiecraft
archives_name = create_more_farmables
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.19.2

# Dependencies
architectury_api_version = 6.6.92
fabric_loader_version = 0.18.4
fabric_api_version = 0.77.0+1.19.2
forge_version = 1.19.2-43.5.1
resourcefullib_version = 1.1.23
botarium_version = 1.8.2
