org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod info
mod_version = 1.0.0
maven_group = net.rockiecraft
archives_name = create_more_farmables
enabled_platforms = fabric,forge

minecraft_version = 1.19.2

# Modloader Versions
forge_version = 1.19.2-43.5.1
fabric_loader_version = 0.18.4
fabric_api_version = 0.77.0+1.19.2

# Dependencies
architectury_api_version = 6.6.92
resourcefullib_version = 1.1.23
resourceful_config_version = 1.0.20
modmenu_version=4.2.0-beta.2
jei_version = 11.8.1.1034

# Create Forge
create_forge_version = 0.5.1.i-59
flywheel_version = 0.6.11-22
registrate_version = MC1.19-1.1.5

# Create Fabric
create_fabric_version = 0.5.1-i-build.1630+mc1.19.2
flywheel_fabric_version = 0.6.11-9
registrate_fabric_version = 1.1.58-MC1.19.2
milk_lib_version = 1.0.51
port_lib_version = 2.1.1453
port_lib_modules = accessors,base,entity,extensions,fake_players,networking,obj_loader,tags,transfer
forge_config_api_port_version = 4.2.11
reach_entity_attributes_version = 2.3.0


