modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Rockiecraft/Create-More-Farmables/issues"
license="MIT"

[[mods]]
modId = "create_more_farmables"
version = "${version}"
displayURL="https://modrinth.com/mod/create-more-farmables"
displayName = "Create: More Farmables"
authors = "RockieFT or Rockiecraft"
logoFile= "logo.png"
description = '''
A Create Addon that brings full automation to More Items, More Blocks, More Fluids, More Mods
'''
#logoFile = ""

[[dependencies.create_more_farmables]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_more_farmables]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_more_farmables]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.create_more_farmables]]
modId = "botarium"
mandatory = true
versionRange = "[2.3.3, )"
ordering = "AFTER"
side = "BOTH"

[[dependencies.create_more_farmables]]
modId="resourcefullib"
mandatory=true
versionRange="[2.1.23,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_more_farmables]]
modId="create"
mandatory=true
versionRange="[6.0.7,6.1.0)"
ordering="NONE"
side="BOTH"

[[dependencies.create_more_farmables]]
modId="create_enchantment_industry"
mandatory=false
versionRange="{1.2.9.d,}"
ordering="NONE"
side="BOTH"

[[dependencies.create_more_farmables]]
modId="cmr"
mandatory=false
versionRange="{1.0.2,}"
ordering="NONE"
side="BOTH"