modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="create_more_farmables"
version="${mod_version}"
displayName="Create: More Farmables"
authors="${mod_authors}"
logoFile="logo.png"
description='''${mod_description}'''
[[dependencies.create_more_farmables]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
[[dependencies.create_more_farmables]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_more_farmables]]
modId="create"
mandatory=true
versionRange="{1.20.1_0.5.1.f,}"
ordering="NONE"
side="BOTH"
[[dependencies.create_more_farmables]]
modId="create_enchantment_industry"
mandatory=false
versionRange="{1.2.9.d,}"
ordering="NONE"
side="BOTH"
[[dependencies.create_more_farmables]]
modId="cmr"
mandatory=false
versionRange="{1.0.2,}"
ordering="NONE"
side="BOTH"

