plugins {
    id 'dev.architectury.loom' version '1.11-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id "io.github.pacifistmc.forgix" version "2.+"
    id 'com.gradleup.shadow' version '8.3.6' apply false
    id "maven-publish"
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version

    repositories {
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }
        maven {
            name = "Resourceful Maven"
            description = "ResourcefulLib & ResourcefulConfig"
            url = "https://maven.teamresourceful.com/repository/maven-public/"
        }
        maven {
            name = "Terraformers"
            url = "https://maven.terraformersmc.com/"
        }
        maven { url = "https://maven.neoforged.net" }
        maven { url = "https://maven.neoforged.net/releases/" }
        maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
        maven { url = "https://mvn.devos.one/snapshots/" } // Create, Porting Lib, Forge Tags, Milk Lib, Registrate
        maven { url = "https://mvn.devos.one/releases/" } // Porting Lib
        maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" } // Forge Config API
        maven { url = "https://maven.jamieswhiteshirt.com/libs-release" } // Reach Entity Attributes
        maven { url = "https://maven.blamejared.com" } // JEI
        maven { url = "https://maven.ithundxr.dev/mirror" } // Registrate (see wiki.createmod.net/developers/depend-on-create/forge-1.20.1)

    }
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'

    base {
        archivesName = "$rootProject.archives_name-$project.name"
    }

    repositories {
        // See https://docs.gradle.org/current/userguide/declaring_repositories.html
        // for more information about repositories.
    }

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
        mappings loom.layered() {
            officialMojangMappings()
            parchment("org.parchmentmc.data:parchment-${rootProject.minecraft_version}:2023.09.03@zip")
        }
    }

    java {
        // if it is present.
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 17
    }

    // Configure Maven publishing.
    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = base.archivesName.get()
                from components.java
            }
        }

        // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
        repositories {
            // Notice: This block does NOT have the same function as the block in the top level.
            // The repositories here will be used for publishing your artifact, not for
            // retrieving dependencies.
        }
    }
}

forgix {
   destinationDirectory = layout.projectDirectory.dir("../build/libs")
    archiveClassifier = "combo"
      archiveVersion = minecraft_version+"-"+mod_version
      archiveBaseName = "c_more_farmables"
    fabric()
    forge()

    // Optional: Point directly to the remapped jars if auto-detect fails

    fabric {
        inputJar = project(":fabric").tasks.remapJar.archiveFile
    }
    forge {
        inputJar = project(":forge").tasks.remapJar.archiveFile
    }
    autoRun = true
}
tasks.named('mergeJars') {
    dependsOn tasks.named('build')
}
build.dependsOn(":fabric:build")
build.dependsOn(":forge:build")
