org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# minecraft
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.100
loader_version_range=[1,)

## Mod Properties
archives_name = c_more_farmables_beta
mod_id=create_more_farmables
mod_name=Create: More Farmables
mod_license=MIT
mod_version=1.21.1-0.9.0
mod_group_id=com.rockiecraft.create_more_farmables

# Create dependencies
create_version = 6.0.10-280
ponder_version = 1.0.82
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67

# Resourcelib
resourcefullib_version = 2.1.29
resourceful_config_version = 1.0.0
jei_version=19.21.0.247
