pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            // Location of the maven that hosts Team Resourceful's jars.
            name = "Team Resourceful Maven"
            url = "https://maven.teamresourceful.com/repository/maven-public/"
        }
        maven { url = "https://maven.createmod.net" }
        maven {
            // location of the maven that hosts JEI files since January 2023
            name = "Jared's maven"
            url = "https://maven.blamejared.com/"
        }
        maven {
            // location of a maven mirror for JEI files, as a fallback
            name = "ModMaven"
            url = "https://modmaven.dev"
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
